AllCops:
  TargetRubyVersion: 3.1.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/MethodParameterName:
  Enabled: false
